describe("Japanese deinflector", function()
    local Deinflector

    setup(function()
        require("commonrequire")
        package.path = "plugins/japanese.koplugin/?.lua;" .. package.path
        Deinflector = require("deinflector"):new()
    end)

    --- Check that deinflecting `source` produces `term` somewhere in the results.
    -- Uses deinflectVerbatim (no kana conversion) for precise rule testing.
    local function assertDeinflects(source, term, reason_hint)
        local results = Deinflector:deinflectVerbatim(source)
        local found_terms = {}
        for _, r in ipairs(results) do
            if r.term == term then
                return r -- success
            end
            table.insert(found_terms, r.term)
        end
        error(string.format(
            "deinflecting %q: expected %q%s but only got: %s",
            source, term,
            reason_hint and (" via " .. reason_hint) or "",
            table.concat(found_terms, ", ")
        ), 2)
    end

    --- Check that deinflecting `source` with full text conversions produces `term`.
    local function assertDeinflectsFull(source, term, reason_hint)
        local results = Deinflector:deinflect(source)
        for _, r in ipairs(results) do
            if r.term == term then
                return r -- success
            end
        end
        error(string.format(
            "full deinflecting %q: expected %q%s not found in results",
            source, term,
            reason_hint and (" via " .. reason_hint) or ""
        ), 2)
    end

    -- ================================================================
    -- i-adjectives (adj-i)
    -- ================================================================
    describe("i-adjectives", function()
        -- 高い (takai, expensive/tall)
        it("should handle identity", function()
            assertDeinflects("高い", "高い")
        end)
        it("negative: 高くない → 高い", function()
            assertDeinflects("高くない", "高い")
        end)
        it("past: 高かった → 高い", function()
            assertDeinflects("高かった", "高い")
        end)
        it("te-form: 高くて → 高い", function()
            assertDeinflects("高くて", "高い")
        end)
        it("adverbial: 高く → 高い", function()
            assertDeinflects("高く", "高い")
        end)
        it("conditional: 高ければ → 高い", function()
            assertDeinflects("高ければ", "高い")
        end)
        it("noun form: 高さ → 高い", function()
            assertDeinflects("高さ", "高い")
        end)
        it("-sou: 高そう → 高い", function()
            assertDeinflects("高そう", "高い")
        end)
        it("-sugiru: 高すぎる → 高い", function()
            assertDeinflects("高すぎる", "高い")
        end)
        it("-tara: 高かったら → 高い", function()
            assertDeinflects("高かったら", "高い")
        end)
        it("-tari: 高かったり → 高い", function()
            assertDeinflects("高かったり", "高い")
        end)
        it("polite negative: 高くありません → 高い", function()
            assertDeinflects("高くありません", "高い")
        end)
        it("-ki (archaic): 高き → 高い", function()
            assertDeinflects("高き", "高い")
        end)

        -- 美しい (utsukushii, beautiful) - tests multi-kana stems
        it("negative: 美しくない → 美しい", function()
            assertDeinflects("美しくない", "美しい")
        end)
        it("past: 美しかった → 美しい", function()
            assertDeinflects("美しかった", "美しい")
        end)
        it("-ge: 美しげ → 美しい", function()
            assertDeinflects("美しげ", "美しい")
        end)
    end)

    -- ================================================================
    -- Ichidan verbs (v1) — "ru-verbs"
    -- ================================================================
    describe("ichidan verbs", function()
        -- 食べる (taberu, eat)
        it("should handle identity", function()
            assertDeinflects("食べる", "食べる")
        end)
        it("negative: 食べない → 食べる", function()
            assertDeinflects("食べない", "食べる")
        end)
        it("past: 食べた → 食べる", function()
            assertDeinflects("食べた", "食べる")
        end)
        it("te-form: 食べて → 食べる", function()
            assertDeinflects("食べて", "食べる")
        end)
        it("polite: 食べます → 食べる", function()
            assertDeinflects("食べます", "食べる")
        end)
        it("polite negative: 食べません → 食べる", function()
            assertDeinflects("食べません", "食べる")
        end)
        it("polite past: 食べました → 食べる", function()
            assertDeinflects("食べました", "食べる")
        end)
        it("polite past negative: 食べませんでした → 食べる", function()
            assertDeinflects("食べませんでした", "食べる")
        end)
        it("polite volitional: 食べましょう → 食べる", function()
            assertDeinflects("食べましょう", "食べる")
        end)
        it("conditional: 食べれば → 食べる", function()
            assertDeinflects("食べれば", "食べる")
        end)
        it("volitional: 食べよう → 食べる", function()
            assertDeinflects("食べよう", "食べる")
        end)
        it("imperative: 食べろ → 食べる", function()
            assertDeinflects("食べろ", "食べる")
        end)
        it("imperative (yo): 食べよ → 食べる", function()
            assertDeinflects("食べよ", "食べる")
        end)
        it("causative: 食べさせる → 食べる", function()
            assertDeinflects("食べさせる", "食べる")
        end)
        it("passive/potential: 食べられる → 食べる", function()
            assertDeinflects("食べられる", "食べる")
        end)
        it("-tai: 食べたい → 食べる", function()
            assertDeinflects("食べたい", "食べる")
        end)
        it("-nasai: 食べなさい → 食べる", function()
            assertDeinflects("食べなさい", "食べる")
        end)
        it("-sou: 食べそう → 食べる", function()
            assertDeinflects("食べそう", "食べる")
        end)
        it("-sugiru: 食べすぎる → 食べる", function()
            assertDeinflects("食べすぎる", "食べる")
        end)
        it("-tara: 食べたら → 食べる", function()
            assertDeinflects("食べたら", "食べる")
        end)
        it("-tari: 食べたり → 食べる", function()
            assertDeinflects("食べたり", "食べる")
        end)
        it("-zu: 食べず → 食べる", function()
            assertDeinflects("食べず", "食べる")
        end)
        it("-nu: 食べぬ → 食べる", function()
            assertDeinflects("食べぬ", "食べる")
        end)
        it("imperative negative: 食べるな → 食べる", function()
            assertDeinflects("食べるな", "食べる")
        end)
        it("-chau: 食べちゃう → 食べる", function()
            assertDeinflects("食べちゃう", "食べる")
        end)
        it("-chimau: 食べちまう → 食べる", function()
            assertDeinflects("食べちまう", "食べる")
        end)

        -- 見る (miru, see) — short ichidan stem
        it("negative: 見ない → 見る", function()
            assertDeinflects("見ない", "見る")
        end)
        it("te-form: 見て → 見る", function()
            assertDeinflects("見て", "見る")
        end)
        it("past: 見た → 見る", function()
            assertDeinflects("見た", "見る")
        end)
    end)

    -- ================================================================
    -- Godan verbs (v5) — "u-verbs", all kana endings
    -- ================================================================
    describe("godan verbs", function()
        -- 書く (kaku, write) — ku ending
        describe("ku-ending: 書く", function()
            it("negative: 書かない → 書く", function()
                assertDeinflects("書かない", "書く")
            end)
            it("past: 書いた → 書く", function()
                assertDeinflects("書いた", "書く")
            end)
            it("te-form: 書いて → 書く", function()
                assertDeinflects("書いて", "書く")
            end)
            it("polite: 書きます → 書く", function()
                assertDeinflects("書きます", "書く")
            end)
            it("conditional: 書けば → 書く", function()
                assertDeinflects("書けば", "書く")
            end)
            it("volitional: 書こう → 書く", function()
                assertDeinflects("書こう", "書く")
            end)
            it("imperative: 書け → 書く", function()
                assertDeinflects("書け", "書く")
            end)
            it("potential: 書ける → 書く", function()
                assertDeinflects("書ける", "書く")
            end)
            it("passive: 書かれる → 書く", function()
                assertDeinflects("書かれる", "書く")
            end)
            it("causative: 書かせる → 書く", function()
                assertDeinflects("書かせる", "書く")
            end)
            it("-tai: 書きたい → 書く", function()
                assertDeinflects("書きたい", "書く")
            end)
            it("-zu: 書かず → 書く", function()
                assertDeinflects("書かず", "書く")
            end)
            it("-tara: 書いたら → 書く", function()
                assertDeinflects("書いたら", "書く")
            end)
            it("-tari: 書いたり → 書く", function()
                assertDeinflects("書いたり", "書く")
            end)
            it("masu stem: 書き → 書く", function()
                assertDeinflects("書き", "書く")
            end)
        end)

        -- 泳ぐ (oyogu, swim) — gu ending
        describe("gu-ending: 泳ぐ", function()
            it("negative: 泳がない → 泳ぐ", function()
                assertDeinflects("泳がない", "泳ぐ")
            end)
            it("past: 泳いだ → 泳ぐ", function()
                assertDeinflects("泳いだ", "泳ぐ")
            end)
            it("te-form: 泳いで → 泳ぐ", function()
                assertDeinflects("泳いで", "泳ぐ")
            end)
            it("polite: 泳ぎます → 泳ぐ", function()
                assertDeinflects("泳ぎます", "泳ぐ")
            end)
            it("conditional: 泳げば → 泳ぐ", function()
                assertDeinflects("泳げば", "泳ぐ")
            end)
            it("potential: 泳げる → 泳ぐ", function()
                assertDeinflects("泳げる", "泳ぐ")
            end)
            it("causative: 泳がせる → 泳ぐ", function()
                assertDeinflects("泳がせる", "泳ぐ")
            end)
        end)

        -- 話す (hanasu, speak) — su ending
        describe("su-ending: 話す", function()
            it("negative: 話さない → 話す", function()
                assertDeinflects("話さない", "話す")
            end)
            it("past: 話した → 話す", function()
                assertDeinflects("話した", "話す")
            end)
            it("te-form: 話して → 話す", function()
                assertDeinflects("話して", "話す")
            end)
            it("polite: 話します → 話す", function()
                assertDeinflects("話します", "話す")
            end)
            it("conditional: 話せば → 話す", function()
                assertDeinflects("話せば", "話す")
            end)
            it("potential: 話せる → 話す", function()
                assertDeinflects("話せる", "話す")
            end)
        end)

        -- 待つ (matsu, wait) — tsu ending
        describe("tsu-ending: 待つ", function()
            it("negative: 待たない → 待つ", function()
                assertDeinflects("待たない", "待つ")
            end)
            it("past: 待った → 待つ", function()
                assertDeinflects("待った", "待つ")
            end)
            it("te-form: 待って → 待つ", function()
                assertDeinflects("待って", "待つ")
            end)
            it("polite: 待ちます → 待つ", function()
                assertDeinflects("待ちます", "待つ")
            end)
            it("conditional: 待てば → 待つ", function()
                assertDeinflects("待てば", "待つ")
            end)
        end)

        -- 死ぬ (shinu, die) — nu ending
        describe("nu-ending: 死ぬ", function()
            it("negative: 死なない → 死ぬ", function()
                assertDeinflects("死なない", "死ぬ")
            end)
            it("past: 死んだ → 死ぬ", function()
                assertDeinflects("死んだ", "死ぬ")
            end)
            it("te-form: 死んで → 死ぬ", function()
                assertDeinflects("死んで", "死ぬ")
            end)
            it("polite: 死にます → 死ぬ", function()
                assertDeinflects("死にます", "死ぬ")
            end)
            it("conditional: 死ねば → 死ぬ", function()
                assertDeinflects("死ねば", "死ぬ")
            end)
        end)

        -- 遊ぶ (asobu, play) — bu ending
        describe("bu-ending: 遊ぶ", function()
            it("negative: 遊ばない → 遊ぶ", function()
                assertDeinflects("遊ばない", "遊ぶ")
            end)
            it("past: 遊んだ → 遊ぶ", function()
                assertDeinflects("遊んだ", "遊ぶ")
            end)
            it("te-form: 遊んで → 遊ぶ", function()
                assertDeinflects("遊んで", "遊ぶ")
            end)
            it("polite: 遊びます → 遊ぶ", function()
                assertDeinflects("遊びます", "遊ぶ")
            end)
            it("conditional: 遊べば → 遊ぶ", function()
                assertDeinflects("遊べば", "遊ぶ")
            end)
        end)

        -- 読む (yomu, read) — mu ending
        describe("mu-ending: 読む", function()
            it("negative: 読まない → 読む", function()
                assertDeinflects("読まない", "読む")
            end)
            it("past: 読んだ → 読む", function()
                assertDeinflects("読んだ", "読む")
            end)
            it("te-form: 読んで → 読む", function()
                assertDeinflects("読んで", "読む")
            end)
            it("polite: 読みます → 読む", function()
                assertDeinflects("読みます", "読む")
            end)
            it("conditional: 読めば → 読む", function()
                assertDeinflects("読めば", "読む")
            end)
        end)

        -- 取る (toru, take) — ru ending (godan, not ichidan)
        describe("ru-ending: 取る", function()
            it("negative: 取らない → 取る", function()
                assertDeinflects("取らない", "取る")
            end)
            it("past: 取った → 取る", function()
                assertDeinflects("取った", "取る")
            end)
            it("te-form: 取って → 取る", function()
                assertDeinflects("取って", "取る")
            end)
            it("polite: 取ります → 取る", function()
                assertDeinflects("取ります", "取る")
            end)
            it("conditional: 取れば → 取る", function()
                assertDeinflects("取れば", "取る")
            end)
        end)

        -- 買う (kau, buy) — u ending
        describe("u-ending: 買う", function()
            it("negative: 買わない → 買う", function()
                assertDeinflects("買わない", "買う")
            end)
            it("past: 買った → 買う", function()
                assertDeinflects("買った", "買う")
            end)
            it("te-form: 買って → 買う", function()
                assertDeinflects("買って", "買う")
            end)
            it("polite: 買います → 買う", function()
                assertDeinflects("買います", "買う")
            end)
            it("conditional: 買えば → 買う", function()
                assertDeinflects("買えば", "買う")
            end)
            it("volitional: 買おう → 買う", function()
                assertDeinflects("買おう", "買う")
            end)
            it("potential: 買える → 買う", function()
                assertDeinflects("買える", "買う")
            end)
        end)

        -- 行く (iku, go) — irregular te/past forms
        describe("irregular: 行く", function()
            it("past: 行った → 行く", function()
                assertDeinflects("行った", "行く")
            end)
            it("te-form: 行って → 行く", function()
                assertDeinflects("行って", "行く")
            end)
            it("-tara: 行ったら → 行く", function()
                assertDeinflects("行ったら", "行く")
            end)
        end)
    end)

    -- ================================================================
    -- Suru verbs (vs)
    -- ================================================================
    describe("suru verbs", function()
        it("negative: しない → する", function()
            assertDeinflects("しない", "する")
        end)
        it("past: した → する", function()
            assertDeinflects("した", "する")
        end)
        it("te-form: して → する", function()
            assertDeinflects("して", "する")
        end)
        it("polite: します → する", function()
            assertDeinflects("します", "する")
        end)
        it("polite negative: しません → する", function()
            assertDeinflects("しません", "する")
        end)
        it("polite past: しました → する", function()
            assertDeinflects("しました", "する")
        end)
        it("polite past negative: しませんでした → する", function()
            assertDeinflects("しませんでした", "する")
        end)
        it("polite volitional: しましょう → する", function()
            assertDeinflects("しましょう", "する")
        end)
        it("conditional: すれば → する", function()
            assertDeinflects("すれば", "する")
        end)
        it("volitional: しよう → する", function()
            assertDeinflects("しよう", "する")
        end)
        it("imperative: しろ → する", function()
            assertDeinflects("しろ", "する")
        end)
        it("imperative (seyo): せよ → する", function()
            assertDeinflects("せよ", "する")
        end)
        it("causative: させる → する", function()
            assertDeinflects("させる", "する")
        end)
        it("passive: される → する", function()
            assertDeinflects("される", "する")
        end)
        it("-tai: したい → する", function()
            assertDeinflects("したい", "する")
        end)
        it("-nasai: しなさい → する", function()
            assertDeinflects("しなさい", "する")
        end)
        it("-sou: しそう → する", function()
            assertDeinflects("しそう", "する")
        end)
        it("-sugiru: しすぎる → する", function()
            assertDeinflects("しすぎる", "する")
        end)
        it("-zu: せず → する", function()
            assertDeinflects("せず", "する")
        end)
        it("-nu: せぬ → する", function()
            assertDeinflects("せぬ", "する")
        end)
        it("-toku: しとく → する", function()
            assertDeinflects("しとく", "する")
        end)
        it("-chau: しちゃう → する", function()
            assertDeinflects("しちゃう", "する")
        end)

        -- 為る kanji variant
        it("imperative (kanji): 為ろ → 為る", function()
            assertDeinflects("為ろ", "為る")
        end)
    end)

    -- ================================================================
    -- Kuru verbs (vk)
    -- ================================================================
    describe("kuru verbs", function()
        -- くる (hiragana)
        it("negative: こない → くる", function()
            assertDeinflects("こない", "くる")
        end)
        it("past: きた → くる", function()
            assertDeinflects("きた", "くる")
        end)
        it("te-form: きて → くる", function()
            assertDeinflects("きて", "くる")
        end)
        it("polite: きます → くる", function()
            assertDeinflects("きます", "くる")
        end)
        it("polite negative: きません → くる", function()
            assertDeinflects("きません", "くる")
        end)
        it("polite past: きました → くる", function()
            assertDeinflects("きました", "くる")
        end)
        it("conditional: くれば → くる", function()
            assertDeinflects("くれば", "くる")
        end)
        it("volitional: こよう → くる", function()
            assertDeinflects("こよう", "くる")
        end)
        it("imperative: こい → くる", function()
            assertDeinflects("こい", "くる")
        end)
        it("causative: こさせる → くる", function()
            assertDeinflects("こさせる", "くる")
        end)
        it("passive: こられる → くる", function()
            assertDeinflects("こられる", "くる")
        end)
        it("potential: これる → くる", function()
            assertDeinflects("これる", "くる")
        end)
        it("-zu: こず → くる", function()
            assertDeinflects("こず", "くる")
        end)
        it("-toku: きとく → くる", function()
            assertDeinflects("きとく", "くる")
        end)
        it("masu stem: き → くる", function()
            assertDeinflects("き", "くる")
        end)

        -- 来る (kanji)
        it("past (kanji): 来た → 来る", function()
            assertDeinflects("来た", "来る")
        end)
        it("te-form (kanji): 来て → 来る", function()
            assertDeinflects("来て", "来る")
        end)
        it("negative (kanji): 来ない → 来る", function()
            assertDeinflects("来ない", "来る")
        end)
        it("polite (kanji): 来ます → 来る", function()
            assertDeinflects("来ます", "来る")
        end)
        it("imperative (kanji): 来い → 来る", function()
            assertDeinflects("来い", "来る")
        end)
    end)

    -- ================================================================
    -- Zuru verbs (vz)
    -- ================================================================
    describe("zuru verbs", function()
        -- 感ずる (kanzuru, to feel)
        it("negative: 感じない → 感ずる", function()
            assertDeinflects("感じない", "感ずる")
        end)
        it("past: 感じた → 感ずる", function()
            assertDeinflects("感じた", "感ずる")
        end)
        it("te-form: 感じて → 感ずる", function()
            assertDeinflects("感じて", "感ずる")
        end)
        it("polite: 感じます → 感ずる", function()
            assertDeinflects("感じます", "感ずる")
        end)
        it("polite negative: 感じません → 感ずる", function()
            assertDeinflects("感じません", "感ずる")
        end)
        it("polite past: 感じました → 感ずる", function()
            assertDeinflects("感じました", "感ずる")
        end)
        it("polite past negative: 感じませんでした → 感ずる", function()
            assertDeinflects("感じませんでした", "感ずる")
        end)
        it("polite volitional: 感じましょう → 感ずる", function()
            assertDeinflects("感じましょう", "感ずる")
        end)
        it("conditional: 感ずれば → 感ずる", function()
            assertDeinflects("感ずれば", "感ずる")
        end)
        it("volitional: 感じよう → 感ずる", function()
            assertDeinflects("感じよう", "感ずる")
        end)
        it("imperative: 感じろ → 感ずる", function()
            assertDeinflects("感じろ", "感ずる")
        end)
        it("imperative (zeyo): 感ぜよ → 感ずる", function()
            assertDeinflects("感ぜよ", "感ずる")
        end)
        it("causative: 感じさせる → 感ずる", function()
            assertDeinflects("感じさせる", "感ずる")
        end)
        it("causative (ze-): 感ぜさせる → 感ずる", function()
            assertDeinflects("感ぜさせる", "感ずる")
        end)
        it("passive: 感じされる → 感ずる", function()
            assertDeinflects("感じされる", "感ずる")
        end)
        it("potential/passive: 感ざれる → 感ずる", function()
            assertDeinflects("感ざれる", "感ずる")
        end)
        it("potential/passive (ze-): 感ぜられる → 感ずる", function()
            assertDeinflects("感ぜられる", "感ずる")
        end)
        it("-tai: 感じたい → 感ずる", function()
            assertDeinflects("感じたい", "感ずる")
        end)
        it("-nasai: 感じなさい → 感ずる", function()
            assertDeinflects("感じなさい", "感ずる")
        end)
        it("-sou: 感じそう → 感ずる", function()
            assertDeinflects("感じそう", "感ずる")
        end)
        it("-sugiru: 感じすぎる → 感ずる", function()
            assertDeinflects("感じすぎる", "感ずる")
        end)
        it("-tara: 感じたら → 感ずる", function()
            assertDeinflects("感じたら", "感ずる")
        end)
        it("-tari: 感じたり → 感ずる", function()
            assertDeinflects("感じたり", "感ずる")
        end)
        it("-zu: 感ぜず → 感ずる", function()
            assertDeinflects("感ぜず", "感ずる")
        end)
        it("-nu: 感ぜぬ → 感ずる", function()
            assertDeinflects("感ぜぬ", "感ずる")
        end)
        it("-toku: 感じとく → 感ずる", function()
            assertDeinflects("感じとく", "感ずる")
        end)
        it("-chau: 感じちゃう → 感ずる", function()
            assertDeinflects("感じちゃう", "感ずる")
        end)
        it("-chimau: 感じちまう → 感ずる", function()
            assertDeinflects("感じちまう", "感ずる")
        end)
    end)

    -- ================================================================
    -- Multi-step deinflection chains
    -- ================================================================
    describe("multi-step chains", function()
        -- te-form + progressive: 食べている → 食べる
        it("progressive: 食べている → 食べる", function()
            assertDeinflects("食べている", "食べる")
        end)
        it("progressive (contracted): 食べてる → 食べる", function()
            assertDeinflects("食べてる", "食べる")
        end)
        it("progressive (おる): 食べておる → 食べる", function()
            assertDeinflects("食べておる", "食べる")
        end)
        it("progressive (contracted おる): 食べとる → 食べる", function()
            assertDeinflects("食べとる", "食べる")
        end)
        -- te-form + shimau
        it("-te + shimau: 食べてしまう → 食べる", function()
            assertDeinflects("食べてしまう", "食べる")
        end)
        -- negative + past (already single-step, but verifies chaining)
        it("negative past: 食べなかった → 食べる", function()
            assertDeinflects("食べなかった", "食べる")
        end)
        -- polite negative past
        it("polite negative past: 食べませんでした → 食べる", function()
            assertDeinflects("食べませんでした", "食べる")
        end)
        -- causative + passive
        it("causative passive: 書かされる → 書く", function()
            assertDeinflects("書かされる", "書く")
        end)
        -- -chau + past (colloquial past completion)
        it("-chau + past: 食べちゃった → 食べる", function()
            assertDeinflects("食べちゃった", "食べる")
        end)

        -- godan te-form + progressive
        it("godan progressive: 書いている → 書く", function()
            assertDeinflects("書いている", "書く")
        end)
        it("godan progressive (contracted): 書いてる → 書く", function()
            assertDeinflects("書いてる", "書く")
        end)

        -- zuru progressive
        it("zuru progressive: 感じている → 感ずる", function()
            assertDeinflects("感じている", "感ずる")
        end)
        it("zuru progressive (contracted): 感じてる → 感ずる", function()
            assertDeinflects("感じてる", "感ずる")
        end)
    end)

    -- ================================================================
    -- Yomitan-specific transforms (not in old Yomichan rule set)
    -- These tests document transforms that Yomitan supports but the
    -- current deinflector does not. They should fail until we port
    -- Yomitan's transform system.
    -- ================================================================
    describe("yomitan transforms", function()

        -- -過ぎる (kanji variant of -すぎる)
        describe("kanji sugiru", function()
            it("ichidan: 食べ過ぎる → 食べる", function()
                assertDeinflects("食べ過ぎる", "食べる")
            end)
            it("godan: 書き過ぎる → 書く", function()
                assertDeinflects("書き過ぎる", "書く")
            end)
            it("adjective: 高過ぎる → 高い", function()
                assertDeinflects("高過ぎる", "高い")
            end)
        end)

        -- -ちゃ (ては contraction without う)
        describe("-cha contraction", function()
            it("ichidan: 食べちゃ → 食べる", function()
                assertDeinflects("食べちゃ", "食べる")
            end)
            it("godan: 書いちゃ → 書く", function()
                assertDeinflects("書いちゃ", "書く")
            end)
        end)

        -- short causative (す/さす)
        describe("short causative", function()
            it("godan ku: 書かす → 書く", function()
                assertDeinflects("書かす", "書く")
            end)
            it("godan mu: 読ます → 読む", function()
                assertDeinflects("読ます", "読む")
            end)
            it("ichidan: 食べさす → 食べる", function()
                assertDeinflects("食べさす", "食べる")
            end)
        end)

        -- -がる (adjective → verb, show feelings)
        describe("-garu", function()
            it("怖がる → 怖い", function()
                assertDeinflects("怖がる", "怖い")
            end)
            it("寒がる → 寒い", function()
                assertDeinflects("寒がる", "寒い")
            end)
        end)

        -- -まい (negative volitional)
        describe("-mai negative volitional", function()
            it("ichidan: 食べまい → 食べる", function()
                assertDeinflects("食べまい", "食べる")
            end)
            it("suru: するまい → する", function()
                assertDeinflects("するまい", "する")
            end)
        end)

        -- -ざる (archaic negative)
        describe("-zaru archaic negative", function()
            it("ichidan: 食べざる → 食べる", function()
                assertDeinflects("食べざる", "食べる")
            end)
            it("godan: 書かざる → 書く", function()
                assertDeinflects("書かざる", "書く")
            end)
        end)

        -- -ねば (hypothetical negative)
        describe("-neba hypothetical", function()
            it("ichidan: 食べねば → 食べる", function()
                assertDeinflects("食べねば", "食べる")
            end)
            it("godan: 書かねば → 書く", function()
                assertDeinflects("書かねば", "書く")
            end)
        end)

        -- -む (archaic volitional)
        describe("-mu archaic volitional", function()
            it("godan: 書かむ → 書く", function()
                assertDeinflects("書かむ", "書く")
            end)
            it("godan: 読まむ → 読む", function()
                assertDeinflects("読まむ", "読む")
            end)
        end)

        -- -さ (nominalization) — already works for 高さ→高い via "noun" rule
        -- but Yomitan formalizes it as a named transform

        -- -んばかり (on the verge of)
        describe("-nbakari", function()
            it("godan: 泣かんばかり → 泣く", function()
                assertDeinflects("泣かんばかり", "泣く")
            end)
        end)

        -- -んとする (intention/about to)
        describe("-ntosuru", function()
            it("suru: せんとする → する", function()
                assertDeinflects("せんとする", "する")
            end)
        end)

        -- Kansai-ben negative (へん/ひん)
        describe("kansai-ben negative", function()
            it("ichidan: 食べへん → 食べる", function()
                assertDeinflects("食べへん", "食べる")
            end)
            it("godan: 書かへん → 書く", function()
                assertDeinflects("書かへん", "書く")
            end)
        end)

        -- n-slang (r→n sound change)
        describe("n-slang", function()
            it("食べんない → 食べる", function()
                assertDeinflects("食べんない", "食べる")
            end)
        end)

        -- volitional slang (っか contraction)
        describe("volitional slang", function()
            it("行こっか → 行く", function()
                assertDeinflects("行こっか", "行く")
            end)
        end)

        -- imperative negative slang (んな)
        describe("imperative negative slang", function()
            it("するんな → する", function()
                assertDeinflects("するんな", "する")
            end)
        end)
    end)

    -- ================================================================
    -- Text conversions (katakana, halfwidth, etc.)
    -- ================================================================
    describe("text conversions", function()
        -- Katakana to hiragana conversion (enabled by default)
        it("katakana input: タベル → 食べる candidate via たべる", function()
            assertDeinflectsFull("タベナイ", "たべない")
        end)
        it("katakana negative: タベナイ deinflects to たべる", function()
            assertDeinflectsFull("タベナイ", "たべる")
        end)

        -- Halfwidth katakana (enabled by default)
        it("halfwidth katakana: ﾀﾍﾞﾙ converts to fullwidth", function()
            assertDeinflectsFull("ﾀﾍﾞﾙ", "タベル")
        end)
    end)
end)
